### ISSUE TITLE
support older S3 authentication

### ISSUE THREAD

**Issue by loomis** [SixSq/hn-prototype-platform#18] opened 2017-05-16 07:10 UTC
Update the S3 support of Onedata to allow access to S3 deployments that use the older S3 authentication mechanisms (primarily Exoscale).

**Comment by retrack** [comment] 2017-05-16 07:12
Patch proposed under https://github.com/exoscale/aws-sdk-cpp/commits/feature/signature-v2

**Comment by loomis** [comment] 2017-05-16 07:12
Exoscale has forked the AWS C++ SDK and added support for the older S3 authentication mechanism. The repository is here: https://github.com/exoscale/aws-sdk-cpp and the specific patch is referenced above.

**Comment by mebster** [comment] 2017-05-18 11:15
@bkryza where are we with this?

**Comment by bkryza** [comment] 2017-05-18 13:55
@mebster We'll be working on that over the next 2 weeks, the issue was that it is not possible to enable in the aws-core-sdk library v2 without disabling support for v4 easily, we have to do some more refactoring in the code...

**Comment by loomis** [comment] 2017-05-22 11:49
@bkryza reported that the proposed patch does allow the older S3 authentication but turns off the new version.  @loomis has asked @retrack (via email, 19/05) whether Exoscale can update their patch to allow both the older and newer authentication methods to be used.

**Comment by retrack** [comment] 2017-05-22 12:26
we do not plan to have a patch that would enable v2 + v4 auth in the AWS SDK. The patch has been done to enable unit tests and end to end testing. A production environment supporting v4 is still planned for later this summer in time for at scale workloads.

**Comment by loomis** [comment] 2017-05-24 07:01
From a discussion with @bkryza yesterday and subsequent follow-up with their developers, Onedata will provide a patched version that allows both the v2 and v4 authentication mechanisms to be supported.  Rough estimate for an internal version is end of the week (26/05).

**Comment by bkryza** [comment] 2017-05-29 09:16
V2 signature support for S3 has been integrated and can be tested using the following dockers:

replace Oneprovider 3.0.0-rc14 version in docker compose Yaml with:
```
onedata/oneprovider:VFS-3233
```
When adding Exoscale storage to Oneprovider, select V2 signature option in Onepanel.


Oneclient:
```
onedata/oneclient:VFS-3233
```

In order to test oneclient using Docker follow these steps:
```
$ docker run --privileged -it onedata/oneclient:VFS-3233 -H ONEPROVIDER_HOSTNAME -t ACCESS_TOKEN -i /mnt/oneclient

# In another terminal
$ docker exec -it DOCKER_ID /bin/bash
```

**Comment by konstan** [comment] 2017-05-29 09:30
@bkryza Thanks.  Validating on our side.

**Comment by konstan** [comment] 2017-05-29 09:59
@bkryza What configuration parameter should be used from the docker-compose file to be able to start the service with S3 v2?  This is the current set of the parameters that we use.

```
          storages:
            S3:
              type: "s3"
              hostname: "${S3_HOSTNAME}"
              bucketName: "${S3_BUCKET}"
              accessKey: "${S3_ACCESS_KEY}"
              secretKey: "${S3_SECRET_KEY}"
              #  insecure: true
```

**Comment by bkryza** [comment] 2017-05-29 11:30
```
signatureVersion: 2
```

**Comment by konstan** [comment] 2017-05-29 11:56
@bkryza Thanks.  
With VFS-3233 we can work with Exoscale S3 v2.  
I will validate it now for regression with v4 on OBS OTC.

**Comment by konstan** [comment] 2017-05-29 12:31
@bkryza 

I've added the second Oneprovider s3-otc (OTC) to the one that I had before s3-exo (Exoscale).
Now when starting docker Oneclient and trying to list /mnt/ directory I'm getting
```
root@5d192d362c58:/tmp# ll /mnt/
^C
ls: /mnt/oneclient: Connection timed out

root@5d192d362c58:/tmp# 
```

Also, going to the providers from Onezone (with "Go to your files") ends up with showing the spinner and being supposedly blocked on authentication (I saw `Authenticating` overlay message once).

<img width="1273" alt="screen shot 2017-05-29 at 14 15 23" src="https://cloud.githubusercontent.com/assets/353767/26549775/e51e4730-447a-11e7-8caf-bfd0f7ad757c.png">

On `s3-exo` I can't see files from `s3-otc` (seeing only the spinner) and visa versa.

**Comment by konstan** [comment] 2017-05-29 12:33
On `s3-otc` Oneprovider UI instance directly, I can perfectly see and manipulate files.

**Comment by konstan** [comment] 2017-05-29 12:51
Here is the Oneclient connected to `s3-otc` Oneprovider (160.44.197.67)

```
root@machine2fe89169-af47-4c16-b587-24e1ca4f4d64:~/getting-started/scenarios/slipstream_s3# docker logs oneclient-1
Connecting to provider '160.44.197.67:5555' using session ID: '16685690766002729148'...
Getting configuration...
Oneclient has been successfully mounted in '/mnt/oneclient'.
root@machine2fe89169-af47-4c16-b587-24e1ca4f4d64:~/getting-started/scenarios/slipstream_s3#
```

and below are the times to list various folders under `/mnt/oneclient/`

```
root@5d192d362c58:/tmp# time ls -l /mnt/oneclient/
ls: /mnt/oneclient/: Connection timed out
ls: /mnt/oneclient/s3-exo: Connection timed out
ls: /mnt/oneclient/s3-otc: Connection timed out
total 0
drwxrwxr-x 1 root root 0 May 29 12:10 s3-exo
drwxrwxr-x 1 root root 0 May 29 12:14 s3-otc

real    3m0.201s
user    0m0.000s
sys     0m0.008s
root@5d192d362c58:/tmp#
```

```
root@5d192d362c58:/tmp# time ls -l /mnt/oneclient/s3-otc/
ls: /mnt/oneclient/s3-otc/: Connection timed out
ls: /mnt/oneclient/s3-otc/vim.png: Connection timed out
total 0
-rw-rw-r-- 1 465351 946935 355708 May 29 12:13 vim.png

real    2m0.245s
user    0m0.000s
sys     0m0.004s
root@5d192d362c58:/tmp#
```

There seems to be really a regression with v2 vs v4 implementation in VFS-3233.

**Comment by bkryza** [comment] 2017-05-29 14:04
@konstan 

Can you check if you have connection from the Docker container to the S3 storages:

```
root@5d192d362c58:/tmp# telnet EXOSCALE_HOST EXOSCALE_PORT
```

**Comment by konstan** [comment] 2017-05-29 14:10
@bkryza 
```
root@5d192d362c58:/tmp# telnet sos.exo.io 443
Trying 159.100.255.216...
Connected to sos.exo.io.
Escape character is '^]'.
^]
telnet> q
Connection closed.
root@5d192d362c58:/tmp#
```

**Comment by bkryza** [comment] 2017-05-29 14:25
@konstan 

Actually it looks like some issue with synchronization between the Oneprovider's - could you send me the logs from both?

**Comment by konstan** [comment] 2017-05-29 21:14
@bkryza I just sent the logs by email.

**Comment by konstan** [comment] 2017-05-30 12:27
@bkryza 
Tested with VFS-3233 and with two providers - Exoscale and OTC.  Looks like everything works between v2 and v4 endpoints (e.g., client can see both spaces and copy files between them).

I'm now checking file replication for https://github.com/SixSq/hn-prototype-platform/issues/25

**Comment by konstan** [comment] 2017-05-30 12:53
@bkryza 
I tried replication between the providers (using `provider_id` as parameter), however the replication fails. I can give you access to the VMs or send logs.  Let me know.

**Comment by loomis** [comment] 2017-05-30 14:38
As stated above, the v2/v4 support is working with the latest Onedata snapshot release.  This will appear in the v15 release which is expected today. 

Once the new release is available, this will need to be retested.

**Comment by konstan** [comment] 2017-06-07 11:03
Validated on our side.  Both S3 v2 and v4 against Exoscale and OTC respectively work in 3.0.0-rc15.
Closing.

**Closed by konstan** 2017-06-07 11:03 UTC
Labels: C03 Cyfronet, C04 Exoscale, P80 HNSciCloud-RHEA, S10 Working, ★★★
